export const employees = [
  {
    personId: 4,
    name: "Charlotte Abbott",
    supervisorId: 9,
    department: "Human Resources",
    jobTitle: "Sr. HR Administrator",
    phone: "801-724-6600 Ext. 123",
    email: "cabbott@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 5,
    name: "Ashley Adams",
    supervisorId: 9,
    department: "Human Resources",
    jobTitle: "HR Administrator",
    phone: "416 555 4730 Ext. 123",
    email: "aadams@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 6,
    name: "Christina Agluinda",
    supervisorId: 9,
    department: "Human Resources",
    jobTitle: "HR Administrator",
    phone: "+61 2 5555 3103 Ext. 123",
    email: "cagluinda@efficientoffice.com",
    location: "Méx, Mexico",
  },
  {
    personId: 7,
    name: "Shannon Anderson",
    supervisorId: 9,
    department: "Human Resources",
    jobTitle: "HR Administrator",
    phone: "801-724-6600 Ext. 123",
    email: "sanderson@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 89,
    name: "Madison Baker",
    supervisorId: 69,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: "+44 207 555 4730 Ext. 143",
    email: "madison@efficientoffice.com",
    location: "Méx, Mexico",
  },
  {
    personId: 70,
    name: "Omar Baldwin",
    supervisorId: 36,
    department: "Customer Success",
    jobTitle: "Customer Success Advocate",
    phone: "801-724-6600 Ext. 1317",
    email: "omar@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 13,
    name: "Cheryl Barnet",
    supervisorId: 8,
    department: "Customer Success",
    jobTitle: "VP of Customer Success",
    phone: "801-724-6600 Ext. 123",
    email: "cbarnet@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 97,
    name: "Chad Burdette",
    supervisorId: 52,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: "801-724-6600 Ext. 1338",
    email: "chad@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 9,
    name: "Jennifer Caldwell",
    supervisorId: 8,
    department: "Human Resources",
    jobTitle: "VP of People",
    phone: "801-724-6600 Ext. 123",
    email: "jcaldwell@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 45,
    name: "Maria Carr",
    supervisorId: null,
    department: null,
    jobTitle: null,
    phone: "801-724-6600 Ext. 1303",
    email: "maria@efficientoffice.com",
    location: null,
  },
  {
    personId: 17,
    name: "Dorothy Chou",
    supervisorId: 8,
    department: "Finance",
    jobTitle: "Chief Financial Officer",
    phone: "801-724-6600 Ext. 123",
    email: "dchou@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 77,
    name: "Dallon Christensen",
    supervisorId: 99,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: "+61 2 5555 3104",
    email: "dallon@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 19,
    name: "Shelly Cluff",
    supervisorId: 10,
    department: "Operations",
    jobTitle: "Executive Assistant",
    phone: "801-724-6600 Ext. 123",
    email: "scluff@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 93,
    name: "Caitlin Corbett",
    supervisorId: 17,
    department: "Finance",
    jobTitle: "Accountant",
    phone: "604-555-3132",
    email: "caitlin@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 68,
    name: "Antonio Cruz",
    supervisorId: 15,
    department: "Marketing",
    jobTitle: "Social Media Marketer",
    phone: "+44 207 555 4730 Ext. 139",
    email: "antonio@efficientoffice.com",
    location: "Argentina",
  },
  {
    personId: 18,
    name: "Javier Cruz",
    supervisorId: 15,
    department: "Marketing",
    jobTitle: "Content Marketer",
    phone: "801-724-6600 Ext. 123",
    email: "jcruz@efficientoffice.com",
    location: "Argentina",
  },
  {
    personId: 60,
    name: "Yasmine Dean",
    supervisorId: 95,
    department: "Customer Success",
    jobTitle: "Software Implementation Specialist",
    phone: "801-724-6600 Ext. 1313",
    email: "yasmine@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 101,
    name: "Anthony Diaz",
    supervisorId: 105,
    department: "Product",
    jobTitle: "Web Designer",
    phone: "801-724-6600 Ext. 1329",
    email: "anthonyd@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 35,
    name: "Aaron Eckerly",
    supervisorId: 36,
    department: "Customer Success",
    jobTitle: "Customer Success Advocate",
    phone: "801-724-6600 Ext. 1296",
    email: "aaron@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 72,
    name: "Nelson Elliott",
    supervisorId: 95,
    department: "Customer Success",
    jobTitle: "Software Implementation Specialist",
    phone: "801-724-6600 Ext. 1319",
    email: "nelson@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 99,
    name: "Michael Fernandez",
    supervisorId: 11,
    department: "Sales",
    jobTitle: "Sales Director",
    phone: "+61 2 5555 3107",
    email: "michaelf@efficientoffice.com",
    location: "Uruguay",
  },
  {
    personId: 53,
    name: "Clark Fuller",
    supervisorId: 16,
    department: "Operations",
    jobTitle: "Customer Care Trainer",
    phone: "801-724-6600 Ext. 1308",
    email: "clark@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 78,
    name: "Haleigh Girard",
    supervisorId: 105,
    department: "Product",
    jobTitle: "Web Designer",
    phone: "801-724-6600 Ext. 1322",
    email: "haleigh@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 61,
    name: "Dwight Goodman",
    supervisorId: 7,
    department: "Human Resources",
    jobTitle: "Technical Recruiter",
    phone: "604-555-3134",
    email: "dwight@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 26,
    name: "Amy Granger",
    supervisorId: 4,
    department: "Customer Success",
    jobTitle: "Customer Retention Manager",
    phone: "801-724-6600 Ext. 1288",
    email: "amy@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 28,
    name: "Andy Graves",
    supervisorId: 4,
    department: "Customer Success",
    jobTitle: "Customer Success Advocate",
    phone: "801-724-6600 Ext. 1290",
    email: "andy@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 112,
    name: "Janice Hall",
    supervisorId: 14,
    department: "Product",
    jobTitle: "Senior Developer",
    phone: "555-555-5555",
    email: "Janice@efficientoffice.com",
    location: "Uruguay",
  },
  {
    personId: 44,
    name: "Marie Hamm",
    supervisorId: 74,
    department: "Product",
    jobTitle: "Front End Developer",
    phone: "801-724-6600 Ext. 1302",
    email: "marie@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 23,
    name: "Darlene Handley",
    supervisorId: 4,
    department: "Marketing",
    jobTitle: "Content Marketer",
    phone: "801-724-6600 Ext. 1286",
    email: "dhandley@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 81,
    name: "Michelle Hannon",
    supervisorId: 49,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: "801-724-6600 Ext. 1325",
    email: "michelle@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 31,
    name: "Sally Harmon",
    supervisorId: 4,
    department: "Operations",
    jobTitle: "Curriculum Designer",
    phone: "801-724-6600 Ext. 1292",
    email: "sally@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 106,
    name: "Jim Harris",
    supervisorId: 17,
    department: "Customer Success",
    jobTitle: "Compliance Auditor",
    phone: "+61 2 5555 3106 Ext. 123",
    email: "james@efficientoffice.com",
    location: "Uruguay",
  },
  {
    personId: 107,
    name: "Holly Hartley",
    supervisorId: 14,
    department: "Product",
    jobTitle: "Senior Developer",
    phone: "801-724-6600 Ext. 123",
    email: "holly@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 104,
    name: "Jake Huang",
    supervisorId: 4,
    department: "Human Resources",
    jobTitle: "HR Specialist",
    phone: "801-724-6600 Ext. 1337",
    email: "jhuang@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 43,
    name: "Adam Hunter",
    supervisorId: 12,
    department: "IT",
    jobTitle: "Systems Genius",
    phone: "801-724-6600 Ext. 1301",
    email: "adam@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 47,
    name: "Michael Jarsdel",
    supervisorId: 14,
    department: "Product",
    jobTitle: "VP of Product",
    phone: "801-724-6600 Ext. 1304",
    email: "michael@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 8,
    name: "Aakash Jhaveri",
    supervisorId: null,
    department: "Operations",
    jobTitle: null,
    phone: "416-724-6600 Ext. 123",
    email: "af.jhaveri@gmail.com",
    location: "Ontario, Canada",
  },
  {
    personId: 95,
    name: "Ellen Karren",
    supervisorId: 13,
    department: "Customer Success",
    jobTitle: "Customer Implementation Manager",
    phone: "801-724-6600 Ext. 1336",
    email: "ellen@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 86,
    name: "Leslie Kay",
    supervisorId: null,
    department: null,
    jobTitle: null,
    phone: "801-724-6600 Ext. 1330",
    email: "leslie@efficientoffice.com",
    location: null,
  },
  {
    personId: 115,
    name: "Richie Lazaro",
    supervisorId: 79,
    department: "Customer Success",
    jobTitle: "Customer Success Advocate",
    phone: null,
    email: "Rlazaro@efficienctoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 24,
    name: "Reggie Miller",
    supervisorId: 11,
    department: "Sales",
    jobTitle: "Sales Director",
    phone: "604-555-3139",
    email: "zack@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 14,
    name: "Maja Pandev",
    supervisorId: 8,
    department: "Product",
    jobTitle: "VP of Product",
    phone: "801-724-6600 Ext. 123",
    email: "mpandev@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 12,
    name: "Eric Pasture",
    supervisorId: 8,
    department: "IT",
    jobTitle: "VP of IT",
    phone: "801-724-6600 Ext. 123",
    email: "epasture@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 69,
    name: "Karin Petty",
    supervisorId: 11,
    department: "Sales",
    jobTitle: "Sales Director",
    phone: "+44 207 555 4730 Ext. 140",
    email: "karin@efficientoffice.com",
    location: "Argentina",
  },
  {
    personId: 79,
    name: "Trey Pickard",
    supervisorId: 95,
    department: "Customer Success",
    jobTitle: "Software Implementation Specialist",
    phone: "801-724-6600 Ext. 1323",
    email: "trey@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 59,
    name: "Warren Poole",
    supervisorId: 4,
    department: "Human Resources",
    jobTitle: "Technical Recruiter",
    phone: "801-724-6600 Ext. 1312",
    email: "warren@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 39,
    name: "Paige Rasmussen",
    supervisorId: 57,
    department: "Product",
    jobTitle: "Senior Developer",
    phone: "+44 207 555 4730 Ext. 134",
    email: "paige@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 57,
    name: "Liam Raynott",
    supervisorId: 47,
    department: "Product",
    jobTitle: "Product Manager",
    phone: "801-724-6600 Ext. 1310",
    email: "liam@efficientoffice.com",
    location: "Méx, Mexico",
  },
  {
    personId: 105,
    name: "Norma Reed",
    supervisorId: 14,
    department: "Product",
    jobTitle: "Sr. Director of UI/UX",
    phone: "801-724-6600 Ext. 1339",
    email: "norma@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 66,
    name: "Susan Roberts",
    supervisorId: 95,
    department: "Customer Success",
    jobTitle: "Software Implementation Specialist",
    phone: "604-555-3138",
    email: "susan@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 102,
    name: "Michael Romney",
    supervisorId: 7,
    department: "Human Resources",
    jobTitle: "Benefits Administrator",
    phone: "604-555-3136",
    email: "michaelr@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 16,
    name: "Jake Ryan",
    supervisorId: 8,
    department: "Operations",
    jobTitle: "VP Learning and Development",
    phone: "801-724-6600 Ext. 123",
    email: "jryan@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 55,
    name: "Gale Sachevich",
    supervisorId: 17,
    department: "Finance",
    jobTitle: "Controller",
    phone: "801-724-6600 Ext. 1309",
    email: "gale@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 10,
    name: "Ryota Saito",
    supervisorId: 8,
    department: "Operations",
    jobTitle: "Chief Operating Officer",
    phone: "801-724-6600 Ext. 123",
    email: "rsaito@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 63,
    name: "Lewis Shelton",
    supervisorId: 5,
    department: "Human Resources",
    jobTitle: "Technical Recruiter",
    phone: "+44 207 555 4730 Ext. 137",
    email: "lewis@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 67,
    name: "Duke Smith",
    supervisorId: 74,
    department: "Product",
    jobTitle: "Front End Developer",
    phone: "801-724-6600 Ext. 1316",
    email: "howard@efficientoffice.com",
    location: "Méx, Mexico",
  },
  {
    personId: 111,
    name: "Graham Thaxton",
    supervisorId: 11,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: null,
    email: "grahamthaxton@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 80,
    name: "Jeff Tobler",
    supervisorId: 12,
    department: "IT",
    jobTitle: "IT Security Engineer",
    phone: "+44 207 555 4730 Ext. 142",
    email: "jeff@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 73,
    name: "Kellie Turner",
    supervisorId: 15,
    department: "Marketing",
    jobTitle: "Demand Generation Manager",
    phone: "801-724-6600 Ext. 1320",
    email: "kellie@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 11,
    name: "Daniel Vance",
    supervisorId: 8,
    department: "Sales",
    jobTitle: "VP of Sales",
    phone: "801-724-6600 Ext. 123",
    email: "dvance@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 58,
    name: "Tiffany Vincent",
    supervisorId: 15,
    department: "Marketing",
    jobTitle: "Writer",
    phone: "801-724-6600 Ext. 1311",
    email: "tiffany@efficientoffice.com",
    location: "Bahamas",
  },
  {
    personId: 25,
    name: "Philip Wagener",
    supervisorId: 4,
    department: "IT",
    jobTitle: "Director of IT",
    phone: "801-724-6600 Ext. 1287",
    email: "philip@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 52,
    name: "Nate Walker",
    supervisorId: 11,
    department: "Sales",
    jobTitle: "Sales Director",
    phone: "801-724-6600 Ext. 1307",
    email: "nate@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 15,
    name: "Trent Walsh",
    supervisorId: 8,
    department: "Marketing",
    jobTitle: "VP of Marketing",
    phone: "801-724-6600 Ext. 123",
    email: "twalsh@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 91,
    name: "Will Woodward",
    supervisorId: 16,
    department: "Operations",
    jobTitle: "Instructional Designer",
    phone: "801-724-6600 Ext. 1333",
    email: "will@efficientoffice.com",
    location: "Ontario, Canada",
  },
  {
    personId: 96,
    name: "Yun Xu",
    supervisorId: 24,
    department: "Sales",
    jobTitle: "Account Executive",
    phone: "604-555-3140",
    email: "yun@efficientoffice.com",
    location: "Bahamas",
  },
];

export default employees;
